GET http://localhost:5062/books
###

POST http://localhost:5062/books
content-type: application/json

{
    "Book_name":"Book4",
    "Auth_name":"Auth4"
}

###

PUT http://localhost:5062/books/4
content-type: application/json

{
    
    "Book_name":"Book4",
    "Auth_name":"Auth4"
}



###
DELETE  http://localhost:5062/books/1